include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - lib/gen/*.gen.dart
    - lib/gen/**/*.dart
    - lib/objectbox.g.dart
    - lib/generated_plugin_registrant.dart
    - .idea
    - .vscode
    - android
    - assets
    - build
    - ios

linter:
  rules:
