name: food
description: Track intake

publish_to: "none"

version: 1.0.9+9

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker:
  file_picker:
  path_provider:
  html:
  flutter_barcode_scanner: 2.0.0
  flutter_neumorphic_plus: 3.3.0
  objectbox: 2.3.1
  objectbox_flutter_libs: 2.3.1
  qr_flutter: 4.1.0
  shared_preferences: 2.2.2
  string_similarity: 2.0.0

dev_dependencies:
  build_runner: 2.4.7
  flutter_lints: 3.0.1
  objectbox_generator: 2.3.1

flutter:
  uses-material-design: true
