name: food
description: Track intake

publish_to: "none"

version: 1.0.8+8

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_barcode_scanner: 2.0.0
  flutter_neumorphic: 3.2.0
  objectbox: 1.5.0
  objectbox_flutter_libs: 1.5.0
  qr_flutter: 4.0.0
  shared_preferences: 2.0.15
  string_similarity: 2.0.0

dev_dependencies:
  build_runner: 2.1.10
  flutter_lints: 2.0.1
  objectbox_generator: 1.5.0

flutter:
  uses-material-design: true
