name: food
description: Track intake

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fl_chart: ^0.36.3
  flutter:
    sdk: flutter
  objectbox: 1.1.1
  objectbox_flutter_libs: 1.1.1

dev_dependencies:
  build_runner: 2.0.6
  objectbox_generator: 1.1.1

flutter:
  uses-material-design: true
